### ISSUE TITLE
NPM Package for importing static binaries

### ISSUE THREAD

**Issue by dgreif** [homebridge/ffmpeg-for-homebridge#1]
**Is your feature request related to a problem? Please describe:**

Users are currently required to install the correct version of the binary for the platform they are on.  This leaves a lot of room for user error, and confusion around where the binary should be placed after it's on their computer.

**Describe the solution you'd like:**

An npm package that could be pulled into any homebridge project and would use the correct binary based on the current platform.  This already exists in the form of https://github.com/eugeneware/ffmpeg-static, but their binaries don't include `libfdk_aac`, which is the main reason my users need ffmpeg.

**Describe alternatives you've considered:**

I could copy the binaries into `homebridge-ring`, but that would make them a lot less maintainable.  I really appreciate that you created this project, and would simply like to leverage the work you have already done to make it super easy for users.

**Comment by oznu** [comment]
What about a post-install script for `homebridge-ring` that downloads ffmpeg for them and places it in the `homebridge-ring` root directory?

That way it won't interfere with existing ffmpeg installations and you can fall back to their system ffmpeg if the download fails or if the users system is not supported.

**Comment by oznu** [comment]
I'm happy to help write such a script.

**Comment by oznu** [comment]
@dgreif,

If you would like to give this a test: https://github.com/oznu/ffmpeg-for-homebridge#plugin-dependency

**Comment by dgreif** [comment]
@oznu it looks great with some quick testing, thank you! I should be able to get an update out for `homebridge-ring` sometime this week.  Thank you so much for your contributions to the homebridge community, you are killing it!

**Comment by dgreif** [comment]
Seems to be working great, thanks @oznu!
