### ISSUE TITLE
SIGILL on BCM2835 Raspberry Pis 

### ISSUE THREAD

**Issue by Sunoo** [homebridge/ffmpeg-for-homebridge#14]
**Describe The Bug:**
I’ve now had a few users reporting that they’re getting SIGILL from this version of FFmpeg when running on a BCM2835-equipped Raspberry Pi (reported on 1B+, Zero, and Zero W). The version available from apt works correctly (though obviously without sound support).

**To Reproduce:**
Try to decode video using this version of FFmpeg on one of the impacted models.

**Expected behavior:**
No SIGILL.

**ffmpeg output:**
An example with a Pi 1B+: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/679
Another example with a Pi Zero: [Debug.txt](https://github.com/homebridge/ffmpeg-for-homebridge/files/4982585/Debug.txt)

**Environment:**

* **Operating System**: Raspbian

I believe I have a Zero W around somewhere, so I may take a crack at figuring this out myself later if I have time.

**Comment by southernprogrammer** [comment]
I can confirm that versions 0.0.5 and 0.0.6 of ffmpeg do not work on the raspberry pi b+. 

I was only able to get the command “ffmpeg” to work with the release 0.0.1. With 0.0.5 and 0.0.6 I am getting an “Illegal instruction (core dumped)” error.

I was in docker on the homebridge image and the ffmpeg that is shipped did not work for the ring plugin. Once I got ffmpeg to work I was still unable to get the ring video to work. I’m wondering if 0.0.1 is built with the correct flags, or if I need to follow up with that plugin creator.

**Comment by Sunoo** [comment]
I had tried and was unable to reproduce the issue, I guess I never updated the ticket and had just told Oznu directly.

Hearing Docker involved changes things a bit, that’s not a scenario I tested when I was trying to get the SIGILL for testing.

Interesting that it 0.0.1 works, not sure what changed since then.
