### ISSUE TITLE
Direct installation for the target platform

### ISSUE THREAD

**Issue by zokl** [homebridge/ffmpeg-for-homebridge#18]
Hello

Is there a way to install the package for the target platform using cross-compilation? In OpenWRT, I create my own IMG and I need to prepare it, so all installation takes place outside the target platform. Is it possible to download the ARM version on the x86 platform?

**Comment by oznu** [comment]
You can download the binaries here:

https://github.com/homebridge/ffmpeg-for-homebridge/releases/tag/v0.0.9

**Comment by zokl** [comment]
> You can download the binaries here:
> 
> https://github.com/homebridge/ffmpeg-for-homebridge/releases/tag/v0.0.9

OK. I will try it.
