### ISSUE TITLE
libmvec.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by bogdanbun** [homebridge/ffmpeg-for-homebridge#2]
**Describe The Bug:**

When installing another package that depends on ffmpeg-for-homebridge I get the following error:

```
~/.npm# npm -g update homebridge-nest-cam2 --unsafe-perm

> ffmpeg-for-homebridge@0.0.3 install /usr/lib/node_modules/homebridge-nest-cam2/node_modules/ffmpeg-for-homebridge
> node install.js

Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-debian-x86_64.tar.gz
100% - Download Complete
/root/.npm/_ffmpeg_for_homebridge/ffmpeg: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
An error occured while testing the downloaded ffmpeg binary.
```

Apparently libmvec was introduced with in glibc 2.22, and my version of Debian goes up to 2.19.

**Operating System**:

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

**Comment by oznu** [comment]
This is only tested on Debian 9 plus. You can install ffmpeg from another source and the plugin will still work.

The ffmpeg instal script this module provides to plugins tests the ffmpeg binary (which is exactly what you see happening in your log) and falls back to the system-installed ffmpeg if it did not work.

https://github.com/Brandawg93/homebridge-nest-cam2/blob/2cb499e102031739326d733b0a06f004402793da/lib/streamer.js#L440

**Comment by bogdanbun** [comment]
I guess my best option to move forward would be upgrade this VM. At the same time, I suggest to add a note to your readme file regarding supported system versions.
