### ISSUE TITLE
Add support for i386

### ISSUE THREAD

**Issue by aifreedom** [homebridge/ffmpeg-for-homebridge#20]
**Is your feature request related to a problem? Please describe:**
I'm running my homebridge on a old Intel Edison board. Its architecture is not the common x86_64 but i386. The package doesn't work in i386 becaues that architecture is not supported.

**Describe the solution you'd like:**
Build a package for i386 and add i386 to the supported architecture list.

**Describe alternatives you've considered:**
I considered building ffmpeg when building my docker image. But it makes rebuilding the image really slow. So I think it would be nice to add it to this package and make it work for everyone else who is also running Homebridge on old devies.

**Additional context:**
I'd like to help or work on it if the maintainer can give me some guidance.

**Comment by oznu** [comment]
I attempted to build ffmpeg for both debian and alpine linux i386 - but both failed due to other dependencies not compiling.

**Comment by aifreedom** [comment]
Thank you for looking into this. I've been trying to build it using ffmpeg-build-script too. I got an error building xvidcore. I managed to fix it by adding a --disable-assembly argument. But I haven't got the whole script to work. What errors do you have now?
