### ISSUE TITLE
unable to run ffmpeg on windows 10 - 32 bit

### ISSUE THREAD

**Issue by Faisalthe01** [homebridge/ffmpeg-for-homebridge#21]
**Describe The Bug:**
i have downloaded the ffmpeg.exe for windows 10 from your download page but it seems to not supported. I believe it says that it would work on 32 Bit system but when i run it, it says

**ffmpeg output:**

```
This version of C:\ffmpeg\bin\ffmpeg.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

```

**Screenshots:**
![Capture](https://user-images.githubusercontent.com/62862684/95830522-83ea9d80-0d83-11eb-88a5-dd5409d5f04d.JPG)

**Environment:**

* **Operating System**:  Windows 10 Pro - 32 Bit

**Comment by oznu** [comment]
See https://github.com/homebridge/ffmpeg-for-homebridge#supported-platforms

Only [x86_64](https://en.m.wikipedia.org/wiki/X86-64) systems are supported by this project. You can still compile and or install ffmpeg from another source and use that instead.

**Comment by Faisalthe01** [comment]
> See https://github.com/homebridge/ffmpeg-for-homebridge#supported-platforms
> 
> Only [x86_64](https://en.m.wikipedia.org/wiki/X86-64) Windows systems are supported by this project. You can still compile and or install ffmpeg from another source and use that instead.

Hey mate. Thanks for getting back. Would you know any easy way to compile the ffmpeg?

**Comment by oznu** [comment]
Not on Windows - the script used to generate the x64 binary is no longer working and Windows development is not my strong point.
