### ISSUE TITLE
Dropped support for High Sierra?

### ISSUE THREAD

**Issue by SafariKC** [homebridge/ffmpeg-for-homebridge#3]
**Describe The Bug:**
Latest version no longer supports High Sierra?

**To Reproduce:**
Install from high Sierra machine (came with dependency with homebridge-ring)

**Expected behavior:**
Expected it to continue to install, is there a technician limitation that showed up? 

**ffmpeg output:**

Won’t install on High Sierra 
**Screenshots:**

**Environment:**

* **Operating System**:  macOS High Sierra

**Comment by oznu** [comment]
This project only ever supported macOS Mojave or later.

You can still install ffmpeg manually from another source and the ring plugin will automatically used that instead.

**Comment by SafariKC** [comment]
Huh - you are correct.  Wonder why it wasn’t skipping it last night - it did tonight closing this out.

**Comment by oznu** [comment]
The installer now checks for Mojave or later.
