### ISSUE TITLE
Add support for Apple Silicon

### ISSUE THREAD

**Issue by jonlonergan** [homebridge/ffmpeg-for-homebridge#30]
Is your feature request related to a problem? Please describe:
I'm running homebridge on an Apple silicon Mac mini. Its architecture is arm64. The package works when homebridge is running in Rosetta on Node.js 14, but doesn't work in Node.js 16 running natively on Apple silicon because that architecture is not supported.

Describe the solution you'd like:
Build a package for Mac arm64 and add arm64 to the supported architecture list.

Describe alternatives you've considered:
I tried building ffmpeg-for-homebridge from a recent pull request that adds Apple silicon support but ran into errors compiling. Though I must admit, I'm new to compiling and could be missing something.

**Comment by donavanbecker** [comment]
currently [this](https://formulae.brew.sh/formula/ffmpeg#default) is the only possible way till #29 is merged.

**Comment by donavanbecker** [comment]
@jonlonergan for the time being if you want to manually download [this](https://github.com/homebridge/ffmpeg-for-homebridge/actions/runs/1417727607) and move it to the `/usr/local/bin` folder. That will work on Apple Silicon. Just tested on Mac mini m1 myself.

**Comment by jonlonergan** [comment]
> @jonlonergan for the time being if you want to manually download the [ffmpeg-darwin-arm64](https://github.com/homebridge/ffmpeg-for-homebridge/actions/runs/1417727607) and move it to the `/usr/local/bin` folder. That will work on Apple Silicon. Just tested on Mac mini m1 myself.

Thank you very much - this helped fix the problem I was experiencing.

**Comment by donavanbecker** [comment]
@jonlonergan was it a specific plugin?

**Comment by jonlonergan** [comment]
> @jonlonergan was it a specific plugin?

@donavanbecker Yes - https://github.com/samemory/homebridge-eufy-security

**Comment by donavanbecker** [comment]
Hey @jonlonergan 

I would download this ffmpeg file and would replace it, since the other one is intel based and uses rosetta 2 where this is built for apple silicon. Trying to get this implemented into the repo.

[ffmpeg.zip](https://github.com/homebridge/ffmpeg-for-homebridge/files/7530459/ffmpeg.zip)

**Comment by simplytoast1** [comment]
> currently [this](https://formulae.brew.sh/formula/ffmpeg#default) is the only possible way till #29 is merged.

It seems #29 was merged in?  Is that true?

**Comment by donavanbecker** [comment]
v0.0.10 has been release with support for Apple Silicon.
