### ISSUE TITLE
Executing ffmpeg on raspabian: No such file or directory

### ISSUE THREAD

**Issue by fcarucci** [homebridge/ffmpeg-for-homebridge#38]
**Describe The Bug:**
/usr/local/bin $ ./ffmpeg 
-bash: ./ffmpeg: No such file or directory

**To Reproduce:**
Execute this command after installing raspabian binaries:
/usr/local/bin $ ./ffmpeg 

**Expected behavior:**
I can execute ffmpeg

**ffmpeg output:**
-bash: ./ffmpeg: No such file or directory

```
Run `ffmpeg` in a terminal window and post the output below
```
/usr/local/bin $ ./ffmpeg 
-bash: ./ffmpeg: No such file or directory

* **Operating System**: 
raspabian

**Comment by Sunoo** [comment]
How did you install it? Did you copy it into /user/bin/local?

Typically this is installed with a NodeJS package and is used by Homebridge plugins. Not sure what you’d be trying to do using this from the terminal instead of the version in apt.

**Comment by oznu** [comment]
This should be resolved.

**Comment by jakubsuchy** [comment]
I am having the same issue. What was specifically fixed? I just installed the latest ...
