### ISSUE TITLE
ffmpeg for homebridge

### ISSUE THREAD

**Issue by Razor5812** [homebridge/ffmpeg-for-homebridge#4]
Good morning all,

Homebridge is installed on a Nas Synology (previously install on a mac mini and having the same problem).
I managed to connect my first 4 cameras but not my video door entry system: Intercom Fibaro.
My intercom video stream works well on my internet explorer and on VLC.

When I include the intercom in Homebridge, it returns to me: "ERROR: FFmpeg exited with code 1"

Here is the config files :
{
"name": "Portail",
"videoConfig": {
"source": "-re -f mjpeg -i http://login:Mdp@192.168.0.111:1111/live/mjpeg",
"stillImageSource": "-i http://login:Mdp@192.168.0.111:1111/live/jpeg",
"maxStreams": 1,
"maxWidth": 720,
"maxHeight": 576,
"maxFPS": 30,
"vcodec": "h264",
"audio": true,
"debug": true
}

Here is the debug file:

Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url http://Login:Mdp@192.168.0.111:1111/live/mjpeg.
Applying option re (read input at native frame rate) with argument 1.
Applying option f (force format) with argument mjpeg.
Successfully parsed a group of options.
Opening an input file: http://Login:Mdp@192.168.0.111:1111/live/mjpeg.

[mjpeg @ 0x7efc56f1c140] Opening 'http://Login:Mdp@192.168.0.111:1111/live/mjpeg' for reading

[http @ 0x7efc56f1cac0] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy,data'

[tcp @ 0x7efc56f1cf40] Original list of addresses:
[tcp @ 0x7efc56f1cf40] Address 192.168.0.111 port 1111
[tcp @ 0x7efc56f1cf40] Interleaved list of addresses:
[tcp @ 0x7efc56f1cf40] Address 192.168.0.111 port 1111
[tcp @ 0x7efc56f1cf40] Starting connection attempt to 192.168.0.111 port 1111

[tcp @ 0x7efc56f1cf40] Successfully connected to 192.168.0.111 port 1111

[http @ 0x7efc56f1cac0] request: GET /live/mjpeg HTTP/1.1
User-Agent: Lavf/58.38.100
Accept: /
Range: bytes=0-
Connection: close
Host: 192.168.0.111:1111
Icy-MetaData: 1

http://Login:Mdp@192.168.0.111:1111/live/mjpeg: End of file

[4/19/2020, 3:56:10 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by vswee** [comment]
@Razor5812 Would you confirm that you have no other version of FFmpeg installed on the machine.
