### ISSUE TITLE
FFmpeg process creation failed: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT

### ISSUE THREAD

**Issue by sommo** [homebridge/ffmpeg-for-homebridge#48]
Hi all,
once updated the docker image, all works except tte ffmpeg, i get this for all the cameras:

FFmpeg process creation failed: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT

any ideas?
Thank you

**Comment by oznu** [comment]
Uninstall / reinstall the plugin

**Comment by Xusqui** [comment]
Hi there!

As I had the exact same issue, I uninstalled / Reinstalled the plug-in, reconfigured and now my Home App won't find the cameras when trying to add new devices.

Any thoughts on this?
