### ISSUE TITLE
close stream on install

### ISSUE THREAD

**Issue by NebzHB** [homebridge/ffmpeg-for-homebridge#5]
Dears,

on install, i'm receiving an error :
```
100%
100%
-
Download Complete
events.js:180 throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
 ^ TypeError [ERR_INVALID_ARG_TYPE]: 
 The "listener" argument must be of type Function at _addListener (events.js:180:11) 
 at WriteStream.addListener (events.js:240:10) 
 at WriteStream.close (fs.js:2302:10) 
 at WriteStream.file.on (/var/www/html/plugins/homebridge/resources/node_modules/ffmpeg-for-homebridge/install.js:128:14) 
 at WriteStream.emit (events.js:164:20) 
 at finishMaybe (_stream_writable.js:605:14) 
 at afterWrite (_stream_writable.js:456:3) 
 at onwrite (_stream_writable.js:446:7) 
 at fs.js:2246:5 
 at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5) 
 npm ERR!  code ELIFECYCLE npm ERR! errno 1 
 npm ERR!  ffmpeg-for-homebridge@0.0.4 install: node install.js` 
 npm ERR!  Exit status 1 
 npm ERR! 
 npm ERR!  Failed at the ffmpeg-for-homebridge@0.0.4 install script. 
 npm ERR!  This is probably not a problem with npm.  There is likely additional logging output above. 
 npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2020-04-30T16_29_56_234Z-debug.log
```

**Comment by donavanbecker** [comment]
what are you install this one?

**Comment by NebzHB** [comment]
Raspbian GNU/Linux 8.0 (jessie)/armhf/armv7l/32bits, nodejs 8.17.0

Upgraded to stretch and its ok !

**Comment by NebzHB** [comment]
the problem happens on some stretch with nodejs 12 too...

i'll investigate (it's some users of my homebridge plugin for jeedom (french domotic software)) and come back if it's related

**Comment by SafariKC** [comment]
I'm seeing failures too - not really sure why suddenly.  open to thoughts.  I'm on MacOS High Sierra which shouldn't even be trying to do the install and fail with a warning but it's not making that far. 

> ffmpeg-for-homebridge@0.0.4 install /usr/local/lib/node_modules/homebridge-nest-cam/node_modules/ffmpeg-for-homebridge
> node install.js

sh: node: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ffmpeg-for-homebridge@0.0.4 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ffmpeg-for-homebridge@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2020-05-18T23_35_20_114Z-debug.log
