### ISSUE TITLE
Update the install package script to use /opt/homebridge/bin/node

### ISSUE THREAD

**Issue by eoghanobrien** [homebridge/ffmpeg-for-homebridge#50]
**Is your feature request related to a problem? Please describe:**
Yes, https://github.com/dgreif/ring/issues/1072 - issue due to this project expecting `node` to be available on the system `$PATH` but homebridge has isolated/bundled `node` from the wider system (reasons available here: https://www.reddit.com/r/homebridge/comments/vusfib/homebridge_and_npm_node_locations_on_raspberry_pi/) ... leading to the `homebridge-ring` plugin failing to install.

**Describe the solution you'd like:**
Update https://github.com/homebridge/ffmpeg-for-homebridge/blob/184e3c10633eea2b3d6c84d34800c572bab0c3e8/package.json#L16-L18

to:

```json
  "scripts": {
    "install": "/opt/homebridge/bin/node install.js"
  },
```

**Describe alternatives you've considered:**
It's possible to workaround the issue introduced here by updating `~/.homebridge/package.json` and running `/opt/homebridge/node npm install` inside the `~/.homebridge` directory.

**Additional context:**
Can't think of anything else.

* [x] Click the "Preview" tab before you submit to ensure the formatting is correct.

**Comment by donavanbecker** [comment]
Don't think this works with macOS though?

**Comment by oznu** [comment]
Node is in the $PATH when running in the Homebridge context.
