### ISSUE TITLE
Support for Alsa as sound input

### ISSUE THREAD

**Issue by macjl** [homebridge/ffmpeg-for-homebridge#7]
**Is your feature request related to a problem? Please describe:**
I’m using internal sound device as sound input for homebridge-camera-ffmpeg. I can’t use your ffmpeg build, because it does not support Alsa as input sound device.
Here is the configuration I’m using :

`-use_wallclock_as_timestamps 1 -thread_queue_size 512 -re -r 6 -s 1280x720 -f video4linux2 -i /dev/video0 -f alsa -i default:CARD=Device`

**Describe the solution you'd like:**
Include Alsa in build options

**Describe alternatives you've considered:**
I’m using my own compiled version of ffmpeg with Alsa included.
Maybe there is an other option to use internal sound device without using Alsa that I don’t know. Feel free to tell me!

**Additional context:**

**Comment by oznu** [comment]
Done for linux builds only. This will be in the next release.

**Comment by oznu** [comment]
Available in 0.0.5

**Comment by macjl** [comment]
Tested. All working as expected. Thank you!
But not yet usable with homebridge-camera-ffmpeg, as it specifies version 0.0.4 and not >=0.0.4
